if not _G.PVEFrame then return end

ApplyDialogBorder(LFDReadyCheckPopup.Border)
ApplyDialogBorder(LFDRoleCheckPopup.Border)
ApplyDialogBorder(LFGDungeonReadyDialog.Border)
ApplyDialogBorder(LFGDungeonReadyStatus.Border)
ApplyDialogBorder(LFGInvitePopup.Border)
ApplyDialogBorder(LFGListApplicationDialog.Border)
ApplyDialogBorder(LFGListInviteDialog.Border)
ApplyDialogBorder(LFGListFrame.EntryCreation.ActivityFinder.Dialog.Border)
ApplyDialogBorder(RolePollPopup.Border)